### ISSUE TITLE
spider custom mask wizard fails

### ISSUE THREAD

**Issue by azazellochg** [biocompwebs/scipion#125]
When I have selected a single average (subset of 1 element) as "Input Image" in spider custom mask protocol, clicking on any wizard button leads to an error:

>Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/sharov/soft/scipion/software/lib/python2.7/lib-tk/Tkinter.py", line 1486, in __call__
    return self.func(*args)
  File "/home/sharov/soft/scipion/pyworkflow/gui/form.py", line 715, in _showWizard
    wizard.show(self.window)
  File "/home/sharov/soft/scipion/pyworkflow/em/packages/spider/wizard.py", line 308, in show
    d = CustomMaskDialog(form.root, provider, protocolParent=protocol)
  File "/home/sharov/soft/scipion/pyworkflow/em/wizard.py", line 418, in __init__
    dialog.Dialog.__init__(self, parent, "Wizard", buttons=buttons, default='Select', **args)
  File "/home/sharov/soft/scipion/pyworkflow/gui/dialog.py", line 87, in __init__
    self.body(bodyFrame)
  File "/home/sharov/soft/scipion/pyworkflow/em/wizard.py", line 437, in body
    self._beforePreview()
  File "/home/sharov/soft/scipion/pyworkflow/em/packages/spider/wizard.py", line 319, in _beforePreview
    imgLocation = self.protocolParent.inputImage.get().getLocation()
**AttributeError: 'SetOfAverages' object has no attribute 'getLocation'**

**Comment by delarosatrevin** [comment]
Solved in commit #bc7e47a. The problem here is that you selected the Set (SetOfAverages in this case) and not the element, even if it was 1-element set. You should select an element inside the set. 

I fixed the validation that avoid the user to do this mistake. When a set is now selected and it is not a valid input, it shows a warning dialog and cancel.
