### ISSUE TITLE
scipion/xmipp cannot read DM3 format 

### ISSUE THREAD

**Issue by rmarabini** [biocompwebs/scipion#129]
Error:

XMIPP_ERROR 32:  No active object in MetaData.
getValue: please provide objId other than -1
File: software/em/xmipp/libraries/data/metadata.cpp line: 209

Traceback (most recent call last):
  File "/home/roberto/Scipion/scipion-code/pyworkflow/apps/pw_program.py", line 57, in <module>
    pwutils.runJob(None, program, params, env=env)
  File "/home/roberto/Scipion/scipion-code/pyworkflow/utils/process.py", line 51, in runJob
    return runCommand(command, env, cwd)
  File "/home/roberto/Scipion/scipion-code/pyworkflow/utils/process.py", line 65, in runCommand
    check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr, env=env, cwd=cwd)
  File "/home/roberto/Scipion/scipion-code/software/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'xmipp_image_header "test-11.dm3"' returned non-zero exit status 32

**Comment by juannavascalvente** [comment]
The DM3 reader has been modified and now when it tries to read a tag that does not exist the tag is skipped.

**Comment by delarosatrevin** [comment]
@juannavascalvente , did you sent this fix to v1.0 branch?
