### ISSUE TITLE
Relion auto-picking (step 2) wizard is not working

### ISSUE THREAD

**Issue by azazellochg** [biocompwebs/scipion#99]
When I try to run any of the two GUI wizards (for threshold or inter-particle distance) in the protocol "Relion - auto-picking (step 2)", I always get an error:

`Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/igbmc/gsharov/soft/scipion/software/lib/python2.7/lib-tk/Tkinter.py", line 1486, in __call__
    return self.func(*args)
  File "/home/igbmc/gsharov/soft/scipion/pyworkflow/gui/form.py", line 715, in _showWizard
    wizard.show(self.window)
  File "/home/igbmc/gsharov/soft/scipion/pyworkflow/em/packages/relion/wizard.py", line 181, in show
    CoordinatesObjectView(autopickProt.getProject(), micFn, coordDir).show()
TypeError: __init__() takes at least 5 arguments (4 given)`

Whether the protocol was finished ot not does not make a difference. The previous (FOM maps generation) step was finished correctly.
PS. The protocol itself runs smoothly though, it's only wizards that dont work.

**Comment by airenzp** [comment]
There was a parameter missing when loading wizard. Now it is solved.
